services:
  web:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile
      args: 
        - USUARIO=pepe
        - PASSWORD=1234
    container_name: ctportfolio
    ports:
      - "8810:80"
